### ISSUE TITLE
Best practice dir structure for dependencies?

### ISSUE THREAD

**Issue by jsoverson** [PolymerElements/seed-element#19]
The method here seems fragile and intrusive (installing all deps in the parent of the dev directory). Are there any ideas for a better practice?

I know it's common to have all dependencies as siblings to the component directory and that adds a layer of difficulty when you have to rely on relative paths for inclusion.

What about something like the following directory structure?

```
my-element
|-- sandbox
|    |-- src
|         |-- my-element.html
+-- .bowerrc
+-- bower.json
```

With the dependency installation occurring in the `sandbox/` dir (only an example) so that dependencies look like this after installation

```
my-element
|-- sandbox
|    |-- src
|    |    |-- my-element.html
|    +-- polymer
|    |    |-- polymer.html
|    +-- platform
|         |-- platform.js
+-- .bowerrc
+-- bower.json
```

The built component (assuming a build process that optimizes and compresses) could then be located at the root of the directory to accommodate the same pattern of accessing deps via the relative sibling directory in a consuming project.

A checkout with the built component would look like this.

```
my-element
|-- sandbox
|    |-- src
|    |    |-- my-element.html
+-- .bowerrc
+-- bower.json
+-- my-element.html
```

I'm not saying this is the best solution, just opening the topic for discussion.

/cc @addyosmani @robdodson @jstrimpel

**Comment by zenorocha** [comment]
[Polyserve](https://github.com/PolymerLabs/polyserve) should fix this problem. I guess this issue can now be closed.
