### ISSUE TITLE
.bowerrc's ../ is dangerous

### ISSUE THREAD

**Issue by nevir** [PolymerElements/seed-element#25]
We're potentially blowing up a user's environment when they naively do a `git clone` followed by `bower install`.

**Comment by klebba** [comment]
Some sort of recommendation on how to structure a suite of elements (in the vein of paper-elements) would be really useful. Right now I'm following what I see in https://github.com/polymer/tools (`pull-all.sh` and `update-repos.sh`) -- is this the best way to construct a development environment spanning across many interrelated components?

**Comment by robdodson** [comment]
We typically recommend you create a directory called `components` and each element is a subdir in there.

ex:

```
components/
|
|-- x-foo/
|-- x-bar/

**Comment by klebba** [comment]
It's difficult to set up a development environment for shared components like this because Bower will overwrite sibling components that may be working copies when you `bower install` (as reported in this ticket). Until a change to Bower (https://github.com/bower/bower/pull/1363) is made, we have to work around using the strategy from `polymer/tools` -- is this recommended?

**Comment by nevir** [comment]
I'd recommend the polymer/tools approach if your project is composed of a bunch of repos, but if it's only one or two, then you _can_ use bower, but you have to be a bit careful:

General strategy for bower, avoiding the bug you mention is to make use of `bower link` to associate the shared components (bower-built symlinks are the one thing that it actually does respect :-/). Not the most pleasant, but at least you avoid specifying your dependencies in two locations that way

(the layout I have on my box is to have a bunch of shared components `git clone`d into `~/code/repos/<repo>` to link from, and then I setup "workspaces" that are managed by bower that I link components into).

**Comment by klebba** [comment]
That's an interesting approach -- thanks for the suggestion!

**Comment by adewinter** [comment]
FWIW, we're running into the same issue as @klebba :  Bower is stomping over our sibling components.  

@nevir the strategy you suggest with linking is a little unfeasible for us.  We have many custom components, and linking every single one on every single machine (and the jenkins-ci env!) seems like a big pain point.  Any recommendations?


(CC @breen-cengage)

**Comment by zenorocha** [comment]
You might want to check [polyserve](https://github.com/PolymerLabs/polyserve).

**Comment by robdodson** [comment]
+1 for polyserve. It's a pretty simple express middleware that you can run
locally or possibly hook into your testing server

**Comment by notwaldorf** [comment]
We're no longer using bowerrc, closing.

**Comment by adewinter** [comment]
Who is "we" and what are you using instead @notwaldorf ?

**Comment by nevir** [comment]
https://github.com/PolymerLabs/polyserve as the solution to that, at least for the common case.

This bowerrc pattern was really problematic for newcomers

**Comment by notwaldorf** [comment]
@adewinter "we" = "this repo", and as @nevir said, polyserve is our recommended solution.

**Comment by robdodson** [comment]
@adewinter I shot a video tutorial on using polyserve if you want to check it out. I think it uses Polymer 0.9 but it works the same in 1.0

https://www.youtube.com/watch?v=p7Q1mQtFGM8&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&index=5

**Comment by adewinter** [comment]
Ok, thanks for the fast feedback guys!  Much appreciated.

**Comment by klebba** [comment]
@robdodson @nevir It looks like polyserve still only handles working copies for single components. There's still no good solution for authoring across working copies for a collection like paper-elements, but bower/bower#1363 has some progress

**Comment by robdodson** [comment]
@justinfagnani would be a good person to look at this :D
