### ISSUE TITLE
Remove license text from the files

### ISSUE THREAD

**Issue by yordis** [PolymerElements/seed-element#65]
I am using the seed for create some components, right now I am not comfortable with that text there all the time. Is there any possibility of removed from the seed? It's fine for me if you put it inside LICENSE but not inside every single file and inside of some production code

**Comment by samccone** [comment]
ref https://github.com/PolymerElements/polymer-starter-kit/issues/227#issuecomment-133706660

**Comment by arthurvr** [comment]
As Sam points out we have exactly the same situation in PSK. I personally also think it's pretty stupid, but there's nothing we can do. Totally not up to me, but the WSK situation seems way more reasonable to me, most files there don't have a license header.

**Comment by robdodson** [comment]
Yeah sorry. We've spoken with our lawyers and this is their recommendation.

**Comment by yordis** [comment]
@robdodson I came from differents culture and I don't understand that much about Licenses so sorry for my ignorance. What happen if I remove those comments? Because I am just using this like a boilerplate.
