### ISSUE TITLE
Adding a section "Linting your element"

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/seed-element#78]
Hi,
I think it would be worth to add a small section explaining how to use ```polylint``` to lint your element even before trying to use ```polyserve```, e.g. calling ```polylint -i seed-element.html``` in the element directory.

**Comment by notwaldorf** [comment]
@MeTaNoV That sounds good! Would you be interested in sending an update to `README.md`?

**Comment by MeTaNoV** [comment]
done! KTAL!

**Comment by robdodson** [comment]
@MeTaNoV :cake: thank you!

**Comment by notwaldorf** [comment]
Fixed in #94
