### ISSUE TITLE
Initial layout broken by some component referenced.

### ISSUE THREAD

**Issue by qm3ster** [PolymerElements/seed-element#87]
How to reproduce: Download any zip, (I tried 1.0.0 and 1.0.6), unzip, bower install, polyserve.
The 'Docs' and 'Demo' buttons are no longer in the top right arranged horizontally, they are now behind the **`<iron-doc-viewer>`**.
This problem appeared sometime in the last 3 hours. Before that everything was ok in this regard.

**Comment by robdodson** [comment]
hm yeah i 'm seeing something weird here.

![screen shot 2015-12-15 at 11 24 42 am](https://cloud.githubusercontent.com/assets/1066253/11821458/7fcef3c4-a31e-11e5-85ae-357bb70ef515.png)

Looking into it

**Comment by qm3ster** [comment]
I am completely new to components, should I even be using the .zip today, 
or is something like `yo polymer:seed` equally up to date?
Is there any difference between that and batch-replacing 'seed-element' within all files?
What do adult humans use in December 2015?

**Comment by robdodson** [comment]
The zip should be fine. `yo polymer:seed` just uses a clone of this project so they would be similar.

**Comment by robdodson** [comment]
@notwaldorf any idea why the `.toolbar-tools` mixin is not being applied to `#topBar` in the iron-component-page?

**Comment by robdodson** [comment]
Can you try deleting `bower_components` and running `bower install` again. Looks like maybe a bad tag got pushed.

**Comment by qm3ster** [comment]
Done. Got new `paper-styles`, `iron-flex-layout` and `webcomponentsjs`.
It is now back to normal.

**Comment by qm3ster** [comment]
Seems really bizarre, because in the past day there's only been https://github.com/webcomponents/webcomponentsjs/releases/tag/v0.7.20 7 hours ago now
https://github.com/PolymerElements/paper-styles/releases/tag/1.1.0 13 hours ago now, 19 minutes after I opened this issue.
One of these two must have fixed it, but it had to be something else that broke it.

**Comment by qm3ster** [comment]
Nvm, it must have been `iron-flex-layout`, since I didn't have it cached but it says
https://github.com/PolymerElements/iron-flex-layout/releases/tag/v1.2.2 is 15 days old. Last release must have been the problem and got removed entirely is my guess.
