### ISSUE TITLE
Consider adding gulp file

### ISSUE THREAD

**Issue by BLamy** [PolymerElements/seed-element#89]
I'd like to see a gulpfile added to the seed element which featured some of the following. 

`gulp demo` - Opens iron-component-page to the demos.
`gulp docs` - Opens iron-component-page to the docs.
`gulp test` - Runs `wct`
`gulp vulcanize` - Flattens the element and all it's dependencies into .dist directory.
`gulp build` - Runs Polybuild
`gulp lint` - Lints the element.
`gulp weight` - Opens chrome to a polydev report

**Comment by justinfagnani** [comment]
Definitely falls in line with our tools thinking. I think we can close this issue on the element, and when I have the right repo started, open a similar issue there. Thanks @BLamy!
